---
title: "Lichess Project"
author: "Ferchero Juan Guillermo (@guilleadhonorem)^[ _Soy sociólogo (FSOC-UBA). Me dedico al analisis de datos en temas como el estudio de la opinión pública, comportamiento electoral, analisis de texto, redes sociales y consumos culturales, todo mediante R y Phyton. Dirijo el Observatorio de Opinión Publica  en_ [ACDES](http://www.acdesweb.org/) _y escribo en_ [mi blog de temas de R](https://rpubs.com/guilleferchero) _y en_ [mi blog de temas de generales](https://bitacoramodernablog.wordpress.com). _Contacto_: guilleferchero@gmail.com]"
date: "Abril de 2021"
output:
  html_document:
    code_download: true
    code_folding: hide
    toc: TRUE
    depth: 5
subtitle: Base para app de analisis de datos Lichess
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Proyecto Lichessapp 

A continuación veremos algunos análisis de los datos que pueden extraerse de la API de [lichess](https://lichess.com). El objetivo de esta publicación es diseñar las visualizaciones para una futura app.

```{r inicio, message=FALSE, warning=FALSE, include=FALSE}
#Limpiamos memoria

rm(list = ls())

#Instalamos Librerías

#install.packages("DT")
library("DT")
library(tidyverse)
library(lubridate)
library(kableExtra)
library(plotly)
library("chessR")

# Levantamos ultimos datos
usuario <- "Guillebarracas"
Datos <- get_raw_lichess(usuario)
#base <- write.csv(Datos, "base.csv")


# limpieza



### tiempo es -3

Datos$WhiteElo <- as.numeric(Datos$WhiteElo)

Datos$BlackElo <- as.numeric(Datos$BlackElo)

Datos <- Datos %>% 
  mutate(Color = case_when(White == "Guillebarracas"~"Blanco",
                           TRUE ~ "Negro" ),
         Elo = case_when(Color == "Blanco" ~ WhiteElo,
                         TRUE ~ BlackElo),
         Elo_Rival = case_when(Color == "Blanco" ~ BlackElo,
                         TRUE ~ WhiteElo),
         Resultado = case_when(Color == "Blanco" & Result == "1-0" ~ "Victoria",
                               Color == "Blanco" & Result == "0-1" ~ "Derrota",
                               Color == "Negro" & Result == "0-1" ~ "Victoria",
                               Color == "Negro" & Result == "1-0" ~ "Derrota",
                               TRUE ~ "Tablas"),
         Fecha = as.Date(ymd(paste0(substr(Date,1,4),substr(Date,6,7),substr(Date,9,10)))),
         Hora = as.numeric(substr(UTCTime,1,2)),
         Hora_arg = case_when(Hora == 3 ~ 0,
                              Hora == 2 ~ 23,
                              Hora == 1 ~ 22,
                              Hora == 0 ~ 21,
                              TRUE ~ (Hora - 3)),
         weekday = wday(Fecha,1),
         Mes = month(Fecha))

Basepract <- Datos %>% 
  head(1000)

write.csv(Basepract,"Basepract.csv")


#definimos desde y hasta

cant <- nrow(Datos)

Desde <- min(Datos$Fecha)

Hasta <- max(Datos$Fecha)

#Definimos colores

negro <- "#0c0c0c"
gris1 <- "#585757"
gris2 <- "#727171"
blanco <- "#f9f9f9"




```

## Resumen

La base contiene `r cant` de partidas jugadas desde `r Desde` hasta `r Hasta` por el usuario `r usuario`

```{r echo=FALSE, message=FALSE, warning=FALSE}


DatosBlitz <-  Datos %>%
                 filter(TimeControl == "300+3")

fig1 <- ggplot(DatosBlitz, aes(x = Fecha, y = Elo))+ #seleccionamos variables a graficar y a colorear
  geom_line(color = "#000066")+
  geom_point(color = "#000066")+
  # geom_smooth(method = 'loess',
  #             formula = 'y ~ x')+
  geom_hline(yintercept = mean(DatosBlitz$Elo),
             color =  "#000066")+
  labs(title = paste0("Partidas Lichess ",Desde," - ",Hasta),
       subtitle = "Evolución Ranking Elo",
       caption = "API Lichess",
       y = "Elo",
       x = "Fecha",
       yintercept = "Promedio")+
  scale_color_manual(values = c("#000066"))+ #coloreamos las lineas
  scale_x_date(date_breaks = "1 month",date_labels = "%b-%y")+
  theme_minimal()+
  theme(plot.title = element_text( hjust = 0.5 , vjust = 0.5),
        plot.subtitle = element_text( hjust = 0.5 , vjust = 0.5))


fig1 <- ggplotly(fig1, dynamicTicks = T) %>%
    layout(
         xaxis = list(rangeslider = list(visible = T),
                      rangeselector=list(
                        buttons=list(
                          list(count=1, label="1m", step="month", stepmode="todate"),
                          list(count=6, label="6m", step="month", stepmode="todate"),
                          list(count=1, label="YTD", step="year", stepmode="todate"),
                          list(count=1, label="1y", step="year", stepmode="backward"),
                          list(step="all", label="Todos")#NO FUNCIONAN LOS BOTONES (Up: Se arreglo con la función "dynamicTicks")
                        ))))

fig1

```

```{r echo=FALSE, message=FALSE, warning=FALSE}



EloPromedio = round(mean(DatosBlitz$Elo),2)

fig2 <- ggplot(DatosBlitz, aes(x = Fecha, y = Elo, color = Resultado, text = paste0("Elo Rival: ",Elo_Rival)))+ #seleccionamos variables a graficar y a colorear
  geom_point()+
  geom_hline(yintercept = EloPromedio,
             color =  gris1, linetype = "dashed", name = "Elo Promedio")+
  annotate(geom = "text",x = Desde, y = EloPromedio+10, label = paste0("      Promedio: ",EloPromedio))+
  labs(title = paste0("Partidas Lichess ",Desde," - ",Hasta),
       subtitle = "Evolución Ranking Elo",
       caption = "API Lichess",
       y = "Elo",
       x = "Fecha",
       yintercept = "Promedio")+
  scale_x_date(date_breaks = "1 month",date_labels = "%b-%y")+
  scale_color_manual(values = c("#b30000","#facd60","#006600"))+
  theme_minimal()+
  theme(plot.title = element_text( hjust = 0.5 , vjust = 0.5),
        plot.subtitle = element_text( hjust = 0.5 , vjust = 0.5))


fig2 <- ggplotly(fig2, dynamicTicks = T) %>%
    layout(#autosize = F, width = 1000, height = 500,
         xaxis = list(rangeslider = list(visible = T),
                      rangeselector=list(
                        buttons=list(
                          list(count=1, label="1m", step="month", stepmode="backward"),
                          list(count=6, label="6m", step="month", stepmode="backward"),
                          list(count=1, label="YTD", step="year", stepmode="todate"),
                          list(count=1, label="1y", step="year", stepmode="backward"),
                          list(step="all")#NO FUNCIONAN LOS BOTONES
                        ))))

fig2



```
